worldName: schoon1
serverName: Schoonheim
password: 

resources: 
  requests:
    memory: "4Gi"
    cpu: "2000m"

image:
  repository: lloesche/valheim-server
  tag: latest

storage:
  kind: persistentVolumeClaim
  hostvol:
    path: /data/valheim
  pvc:
    size: 1Gi

serverStorage:
  kind: persistentVolumeClaim
  hostvol:
    path: /data/valheim-server
  pvc:
    size: 5Gi

networking:
  serviceType: LoadBalancer
  gamePort: 2456
  publishQueryPort: "true"
  nodePort: 30373

extraEnvironmentVars:
  SERVER_ARGS: "-preset normal -modifier portals casual -modifier deathpenalty casual"
  ADMINLIST_IDS: "76561198045918479 76561198049776133"
  #STEAMCMD_ARGS: "-preset easy"


nodeSelector: {}
  
tolerations: {}

# If you utilize priority classes, you can define the priority class for this deployment here
# priorityClassName: my-priority-class-name

# resources:
#   requests:
#     memory: "4Gi"
#     cpu: "2000m"

# extraEnvironmentVars:
#   BACKUPS: true
#   BACKUPS_CRON: "0 * * * *"
#   BACKUPS_MAX_AGE: 3
#   POST_BACKUP_HOOK: "timeout 300 scp -i /extraVolumes/backup-ssh-key/ssh-privatekey -o StrictHostKeyChecking=no @BACKUP_FILE@ myself@example.com:~/valheim_backups/$(basename @BACKUP_FILE@)"

# extraVolumes:
# - type: secret
#   name: backup-ssh-key
#   defaultMode: 0600